// picksData.js
// Akceptuje tablice stringów LUB obiekty { value, label }.

window.PICKS_LISTS = {
  bossNormal: [
    { value: "boss_Artificed Spare Clockwork Component - Coppelia", label: "Artificed Spare Clockwork Component - Coppelia" },
    { value: "boss_Artificed Spare Clockwork Component - Coppelius", label: "Artificed Spare Clockwork Component - Coppelius" },
    { value: "boss_Basalt Pillar", label: "Basalt Pillar" },
    { value: "boss_Cleansing Heart", label: "Cleansing Heart" },
    { value: "boss_Crystalline Bloom", label: "Crystalline Bloom" },
    { value: "boss_Dew of Repudiation", label: "Dew of Repudiation" },
    { value: "boss_Dragonheir's False Fin", label: "Dragonheir's False Fin" },
    { value: "boss_Emperor's Resolution", label: "Emperor's Resolution" },
    { value: "boss_Everflame Seed", label: "Everflame Seed" },
    { value: "boss_Evergloom Ring", label: "Evergloom Ring" },
    { value: "boss_Hoarfrost Core", label: "Hoarfrost Core" },
    { value: "boss_Hurricane Seed", label: "Hurricane Seed" },
    { value: "boss_Juvenile Jade", label: "Juvenile Jade" },
    { value: "boss_Light Guiding Tetrahedron", label: "Light Guiding Tetrahedron" },
    { value: "boss_Lightning Prism", label: "Lightning Prism" },
    { value: "boss_Marionette Core", label: "Marionette Core" },
    { value: "boss_Perpetual Caliber", label: "Perpetual Caliber" },
    { value: "boss_Perpetual Heart", label: "Perpetual Heart" },
    { value: "boss_Pseudo-Stamens", label: "Pseudo-Stamens" },
    { value: "boss_Quelled Creeper", label: "Quelled Creeper" },
    { value: "boss_Riftborn Regalia", label: "Riftborn Regalia" },
    { value: "boss_Runic Fang", label: "Runic Fang" },
    { value: "boss_Smoldering Pearl", label: "Smoldering Pearl" },
    { value: "boss_Storm Beads", label: "Storm Beads" },
    { value: "boss_Cloudseam Scales", label: "Cloudseam Scale" },
    { value: "boss_Majestic Hooked Beak", label: "Majestic Hooked Beak" },
    { value: "boss_Thunderclap Fruitcore", label: "Thunderclap Fruitcore" },
    { value: "boss_Tourbillon Device", label: "Tourbillon Device" },
    { value: "boss_Fontemer Unihorn", label: "Fontemer Unihorn" },
    { value: "boss_Ensnaring Gaze", label: "Ensnaring Gaze" },
    { value: "boss_Fragment of a Golden Melody", label: "Fragment of a Golden Melody" },
    { value: "boss_Gold-Inscribed Secret Source Core", label: "Gold-Inscribed Secret Source Core" },
    { value: "boss_Mark of the Binding Blessing", label: "Mark of the Binding Blessing" },
    { value: "boss_Overripe Flamegranate", label: "Overripe Flamegranate" },
    { value: "boss_Secret Source Airflow Accumulator", label: "Secret Source Airflow Accumulator" },
    { value: "boss_Sparkless Statue Core", label: "Sparkless Statue Core" },
    { value: "boss_Talisman of the Enigmatic Land", label: "Talisman of the Enigmatic Land" },
    { value: "boss_Water That Failed to Transcend", label: "Water That Failed to Transcend" },
    { value: "boss_Precision Kuuvahki Stamping Die", label: "Precision Kuuvahki Stamping Die" },
    { value: "boss_Lightbearing Scale-Feather", label: "Lightbearing Scale-Feather" },
    // ...dopisz kolejne
  ],
  local: [
    { value: "local_Calla Lily", label: "Calla Lily" },
    { value: "local_Wolfhook", label: "Wolfhook" },
    { value: "local_Valberry", label: "Valberry" },
    { value: "local_Cecilia", label: "Cecilia" },
    { value: "local_Windwheel Aster", label: "Windwheel Aster" },
    { value: "local_Philanemo Mushroom", label: "Philanemo Mushroom" },
    { value: "local_Small Lamp Grass", label: "Small Lamp Grass" },
    { value: "local_Dandelion Seed", label: "Dandelion Seed" },
    { value: "local_Jueyun Chili", label: "Jueyun Chili" },
    { value: "local_Noctilucous Jade", label: "Noctilucous Jade" },
    { value: "local_Silk Flower", label: "Silk Flower" },
    { value: "local_Glaze Lily", label: "Glaze Lily" },
    { value: "local_Qingxin", label: "Qingxin" },
    { value: "local_Starconch", label: "Starconch" },
    { value: "local_Violetgrass", label: "Violetgrass" },
    { value: "local_Cor Lapis", label: "Cor Lapis" },
    { value: "local_Clearwater Jade", label: "Clearwater Jade" },
    { value: "local_Sea Ganodermas", label: "Sea Ganoderma" },
    { value: "local_Sakura Bloom", label: "Sakura Bloom" },
    { value: "local_Naku Weed", label: "Naku Weed" },
    { value: "local_Dendrobium", label: "Dendrobium" },
    { value: "local_Onikabuto", label: "Onikabuto" },
    { value: "local_Crystal Marrow", label: "Crystal Marrow" },
    { value: "local_Sango Pearl", label: "Sango Pearl" },
    { value: "local_Amakumo Fruit", label: "Amakumo Fruit" },
    { value: "local_Fluorescent Fungus", label: "Fluorescent Fungus" },
    { value: "local_Rukkhashava Mushrooms", label: "Rukkhashava Mushrooms" },
    { value: "local_Nilotpala Lotus", label: "Nilotpala Lotus" },
    { value: "local_Kalpalata Lotus", label: "Kalpalata Lotus" },
    { value: "local_Padisarah", label: "Padisarah" },
    { value: "local_Henna Berry", label: "Henna Berry" },
    { value: "local_Scarab", label: "Scarab" },
    { value: "local_Sand Grease Pupa", label: "Sand Grease Pupa" },
    { value: "local_Trishiraite", label: "Trishiraite" },
    { value: "local_Mourning Flower", label: "Mourning Flower" },
    { value: "local_Beryl Conch", label: "Beryl Conch" },
    { value: "local_Rainbow Rose", label: "Rainbow Rose" },
    { value: "local_Romaritime Flower", label: "Romaritime Flower" },
    { value: "local_Lumidouce Bell", label: "Lumidouce Bell" },
    { value: "local_Lumitoile", label: "Lumitoile" },
    { value: "local_Subdetection Unit", label: "Subdetection Unit" },
    { value: "local_Lakelight Lily", label: "Lakelight Lily" },
    { value: "local_Spring of the First Dewdrop", label: "Spring of the First Dewdrop" },
    { value: "local_Saurian Claw Succulent", label: "Saurian Claw Succulent" },
    { value: "local_Quenepa Berry", label: "Quenepa Berry" },
    { value: "local_Sprayfeather Gill", label: "Sprayfeather Gill" },
    { value: "local_Brilliant Chrysanthemum", label: "Brilliant Chrysanthemum" },
    { value: "local_Withering Purpurbloom", label: "Withering Purpurbloom" },
    { value: "local_Glowing Hornshroom", label: "Glowing Hornshroom" },
    { value: "local_Dracolite", label: "Dracolite" },
    { value: "local_Skysplit Gembloom", label: "Skysplit Gembloom" },
    { value: "local_Frostlamp Flower", label: "Frostlamp Flower" },
    { value: "local_Moonfall Silver", label: "Moonfall Silver" },
    { value: "local_Portable Bearing", label: "Portable Bearing" },
    // ...dopisz kolejne
  ],
  enemiesAsc: [
    { value: "flower", label: "A Flower Yet to Bloom" },
    { value: "knife", label: "Hunter's Sacrificial Knife" },
    { value: "insignia_fatui", label: "Recruit's Insignia" },
    { value: "rift", label: "Rift Core" },
    { value: "gear_dynamic", label: "Meshing Gear" },
    { value: "secret_source", label: "Axis of the Secret Source" },
    { value: "leafcoil", label: "Refractive Bud" },
    { value: "horn", label: "Heavy Horn" },
    { value: "shell_prism", label: "Cold-Cracked Shellshard" },
    { value: "chaos_gear", label: "Chaos Gear" },
    { value: "chaos_storage", label: "Chaos Storage" },
    { value: "chaos_device", label: "Chaos Device" },
    { value: "fin", label: "Feathery Fin" },
    { value: "concealed", label: "Concealed Claw" },
    { value: "prism_mirror", label: "Dismal Prism" },
    { value: "fungal_spores", label: "Fungal Spores" },
    { value: "fungal_nucleus", label: "Dormant Fungal Nucleus" },
    { value: "mask", label: "Damaged Mask" },
    { value: "prism_clockwork", label: "Damaged Prism" },
    { value: "statuette", label: "Gloomy Statuette" },
    { value: "ley_line", label: "Dead Ley Line Branch" },
    { value: "shell_consecrated", label: "Desiccated Shell" },
    { value: "scroll", label: "Divining Scroll" },
    { value: "tainted_water", label: "Drop of Tainted Water" },
    { value: "nectar", label: "Whopperflower Nectar" },
    { value: "silk", label: "Faded Red Satin" },
    { value: "handguard", label: "Old Handguard" },
    { value: "arrowhead", label: "Firm Arrowhead" },
    { value: "bone_shard", label: "Fragile Bone Shard" },
    { value: "insignia_treasure", label: "Treasure Hoarder Insignia" },
    { value: "ignited", label: "Ignited Stone" },
    { value: "fang", label: "Juvenile Fang" },
    { value: "will", label: "Shard of a Shattered Will" },
    { value: "mist_grass", label: "Mist Grass Pollen" },
    { value: "operative_watch", label: "Old Operative's Pocket Watch" },
    { value: "hilt", label: "Ruined Hilt" },
    { value: "whistle", label: "Sentry's Wooden Whistle" },
    { value: "slime", label: "Slime Condensate" },
    { value: "specter", label: "Spectral Husk" },
    { value: "transoceanic", label: "Transoceanic Pearl" },
    { value: "shaft", label: "Broken Drive Shaft" },
    { value: "mistshroud", label: "Mistshroud Manifestation" },
    { value: "radiant", label: "Lightless Bone" },
    { value: "frostnight", label: "Frostnight's Glimmer" },
    { value: "oprichniki", label: "Tattered Warrant" },
    // ...dopisz kolejne grupy/materialy
  ],
  books: [
    { value: "freedom", label: "Teachings of Freedom" },
    { value: "prosperity", label: "Teachings of Prosperity" },
    { value: "admonition", label: "Teachings of Admonition" },
    { value: "ingenuity", label: "Teachings of Ingenuity" },
    { value: "ballad", label: "Teachings of Ballad" },
    { value: "conflict", label: "Teachings of Conflict" },
    { value: "contention", label: "Teachings of Contention" },
    { value: "diligence", label: "Teachings of Diligence" },
    { value: "elegance", label: "Teachings of Elegance" },
    { value: "equity", label: "Teachings of Equity" },
    { value: "gold", label: "Teachings of Gold" },
    { value: "justice", label: "Teachings of Justice" },
    { value: "kindling", label: "Teachings of Kindling" },
    { value: "light", label: "Teachings of Light" },
    { value: "order", label: "Teachings of Order" },
    { value: "praxis", label: "Teachings of Praxis" },
    { value: "resistance", label: "Teachings of Resistance" },
    { value: "transience", label: "Teachings of Transience" },
    { value: "elysium", label: "Teachings of Elysium" },
    { value: "moonlight", label: "Teachings of Moonlight" },
    { value: "vagrancy", label: "Teachings of Vagrancy" },
    // ...dopisz kolejne serie ksiąg
  ],
  enemiesTal: [
    { value: "flower", label: "A Flower Yet to Bloom" },
    { value: "knife", label: "Hunter's Sacrificial Knife" },
    { value: "insignia_fatui", label: "Recruit's Insignia" },
    { value: "rift", label: "Rift Core" },
    { value: "gear_dynamic", label: "Meshing Gear" },
    { value: "secret_source", label: "Axis of the Secret Source" },
    { value: "leafcoil", label: "Refractive Bud" },
    { value: "horn", label: "Heavy Horn" },
    { value: "shell_prism", label: "Cold-Cracked Shellshard" },
    { value: "chaos_gear", label: "Chaos Gear" },
    { value: "chaos_storage", label: "Chaos Storage" },
    { value: "chaos_device", label: "Chaos Device" },
    { value: "fin", label: "Feathery Fin" },
    { value: "concealed", label: "Concealed Claw" },
    { value: "prism_mirror", label: "Dismal Prism" },
    { value: "fungal_spores", label: "Fungal Spores" },
    { value: "fungal_nucleus", label: "Dormant Fungal Nucleus" },
    { value: "mask", label: "Damaged Mask" },
    { value: "prism_clockwork", label: "Damaged Prism" },
    { value: "statuette", label: "Gloomy Statuette" },
    { value: "ley_line", label: "Dead Ley Line Branch" },
    { value: "shell_consecrated", label: "Desiccated Shell" },
    { value: "scroll", label: "Divining Scroll" },
    { value: "tainted_water", label: "Drop of Tainted Water" },
    { value: "nectar", label: "Whopperflower Nectar" },
    { value: "silk", label: "Faded Red Satin" },
    { value: "handguard", label: "Old Handguard" },
    { value: "arrowhead", label: "Firm Arrowhead" },
    { value: "bone_shard", label: "Fragile Bone Shard" },
    { value: "insignia_treasure", label: "Treasure Hoarder Insignia" },
    { value: "ignited", label: "Ignited Stone" },
    { value: "fang", label: "Juvenile Fang" },
    { value: "will", label: "Shard of a Shattered Will" },
    { value: "mist_grass", label: "Mist Grass Pollen" },
    { value: "operative_watch", label: "Old Operative's Pocket Watch" },
    { value: "hilt", label: "Ruined Hilt" },
    { value: "whistle", label: "Sentry's Wooden Whistle" },
    { value: "slime", label: "Slime Condensate" },
    { value: "specter", label: "Spectral Husk" },
    { value: "transoceanic", label: "Transoceanic Pearl" },
    { value: "shaft", label: "Broken Drive Shaft" },
    { value: "mistshroud", label: "Mistshroud Manifestation" },
    { value: "radiant", label: "Lightless Bone" },
    { value: "frostnight", label: "Frostnight's Glimmer" },
    { value: "oprichniki", label: "Tattered Warrant" },
  ],
  bossWeekly: [
    // --- DOPISZ DO window.PICKS_LISTS.bossNormal ---
{ value: "weekly_dvalin1",    label: "Dvalin's Plume" },
{ value: "weekly_dvalin2",    label: "Dvalin's Claw" },
{ value: "weekly_dvalin3",    label: "Dvalin's Sigh" },

{ value: "weekly_boreas1",    label: "Tail of Boreas" },
{ value: "weekly_boreas2",    label: "Ring of Boreas" },
{ value: "weekly_boreas3",    label: "Spirit Locket of Boreas" },

{ value: "weekly_Childe1",    label: "Tusk of Monoceros Caeli" },
{ value: "weekly_Childe2",    label: "Shard of Foul Legacy" },
{ value: "weekly_Childe3",    label: "Shadow of the Warrior" },

{ value: "weekly_Azhdaha1",   label: "Dragon Lord's Crown" },
{ value: "weekly_Azhdaha2",   label: "Gilded Scale" },
{ value: "weekly_Azhdaha3",   label: "Bloodjade Branch" },

{ value: "weekly_Signora1",   label: "Ashen Heart" },
{ value: "weekly_Signora2",   label: "Hellfire Butterfly" },
{ value: "weekly_Signora3",   label: "Molten Moment" },

{ value: "weekly_Shogun1",    label: "Mudra of the Malefic General" },
{ value: "weekly_Shogun2",    label: "Tears of the Calamitous God" },
{ value: "weekly_Shogun3",    label: "The Meaning of Aeons" },

{ value: "weekly_Scaramouche1", label: "Mirror of Mushin" },
{ value: "weekly_Scaramouche2", label: "Daka's Bell" },
{ value: "weekly_Scaramouche3", label: "Puppet Strings" },

{ value: "weekly_Apep1",      label: "Everamber" },
{ value: "weekly_Apep2",      label: "Primordial Greenbloom" },
{ value: "weekly_Apep3",      label: "Worldspan Fern" },

{ value: "weekly_Narwhal1",   label: "Lightless Mass" },
{ value: "weekly_Narwhal2",   label: "Lightless Eye of the Maelstrom" },
{ value: "weekly_Narwhal3",   label: "Lightless Silk String" },

{ value: "weekly_Knave1",     label: "Silken Feather" },
{ value: "weekly_Knave2",     label: "Fading Candle" },
{ value: "weekly_Knave3",     label: "Denial and Judgment" },

{ value: "weekly_Eroded1",    label: "Eroded Horn" },
{ value: "weekly_Eroded2",    label: "Eroded Sunfire" },
{ value: "weekly_Eroded3",    label: "Eroded Scale-Feather" },

{ value: "weekly_Game1",      label: "Ascended Sample Rook" },
{ value: "weekly_Game2",      label: "Ascended Sample Knight" },
{ value: "weekly_Game3",      label: "Ascended Sample Queen" },
    // ...dopisz kolejne
  ]
};
